# Generated by Django 5.2.7 on 2025-10-10 19:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor')], default='aluno', max_length=20)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_acesso', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biometria.sala')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biometria.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Digital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_b64', models.TextField()),
                ('hash_sha256', models.CharField(editable=False, max_length=64)),
                ('dedo', models.CharField(blank=True, choices=[('indicador_dir', 'Indicador DIR.'), ('polegar_dir', 'Polegar DIR.'), ('medio_dir', 'Médio DIR.'), ('anelar_dir', 'Anelar DIR.'), ('minimo_dir', 'Mínimo DIR.'), ('indicador_esq', 'Indicador ESQ.'), ('polegar_esq', 'Polegar ESQ.'), ('medio_esq', 'Médio ESQ.'), ('anelar_esq', 'Anelar ESQ.'), ('minimo_esq', 'Mínimo ESQ.')], max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitais', to='biometria.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'hash_sha256')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biometria.sala')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biometria.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'sala')},
            },
        ),
    ]
