# Generated by Django 5.2.7 on 2025-10-10 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_b64', models.TextField()),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
