# Generated by Django 5.2.7 on 2026-01-07 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digital',
            name='sensor_id',
            field=models.IntegerField(help_text='ID (1-200) no qual o sensor irá armazenar este template.', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
